//
// ContributorsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire
import AlamofireObjectMapper


open class CoverageLonLatContributorsRequestBuilder: NSObject {
    let currentApi: ContributorsAPI

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel_getCoverageLonLatContributors: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var lat: Double? = nil
    var lon: Double? = nil
    var startPage: Int32? = nil
    var count: Int32? = nil
    var depth: Int32? = nil
    var forbiddenId: [String]? = nil
    var forbiddenUris: [String]? = nil
    var externalCode: String? = nil
    var headsign: String? = nil
    var showCodes: Bool? = nil
    var odtLevel: OdtLevel_getCoverageLonLatContributors? = nil
    var distance: Int32? = nil
    var since: String? = nil
    var until: String? = nil
    var disableGeojson: Bool? = nil
    var filter: String? = nil

    public init(currentApi: ContributorsAPI) {
        self.currentApi = currentApi
    }

    open func withLat(_ lat: Double) -> CoverageLonLatContributorsRequestBuilder {
        self.lat = lat
        return self
    }
    open func withLon(_ lon: Double) -> CoverageLonLatContributorsRequestBuilder {
        self.lon = lon
        return self
    }
    open func withStartPage(_ startPage: Int32) -> CoverageLonLatContributorsRequestBuilder {
        self.startPage = startPage
        return self
    }
    open func withCount(_ count: Int32) -> CoverageLonLatContributorsRequestBuilder {
        self.count = count
        return self
    }
    open func withDepth(_ depth: Int32) -> CoverageLonLatContributorsRequestBuilder {
        self.depth = depth
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]) -> CoverageLonLatContributorsRequestBuilder {
        self.forbiddenId = forbiddenId
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]) -> CoverageLonLatContributorsRequestBuilder {
        self.forbiddenUris = forbiddenUris
        return self
    }
    open func withExternalCode(_ externalCode: String) -> CoverageLonLatContributorsRequestBuilder {
        self.externalCode = externalCode
        return self
    }
    open func withHeadsign(_ headsign: String) -> CoverageLonLatContributorsRequestBuilder {
        self.headsign = headsign
        return self
    }
    open func withShowCodes(_ showCodes: Bool) -> CoverageLonLatContributorsRequestBuilder {
        self.showCodes = showCodes
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel_getCoverageLonLatContributors) -> CoverageLonLatContributorsRequestBuilder {
        self.odtLevel = odtLevel
        return self
    }
    open func withOdtLevel(_ odtLevelValue: String) -> CoverageLonLatContributorsRequestBuilder {
        return withOdtLevel(OdtLevel_getCoverageLonLatContributors(rawValue: odtLevelValue)!);
    }
    open func withDistance(_ distance: Int32) -> CoverageLonLatContributorsRequestBuilder {
        self.distance = distance
        return self
    }
    open func withSince(_ since: String) -> CoverageLonLatContributorsRequestBuilder {
        self.since = since
        return self
    }
    open func withUntil(_ until: String) -> CoverageLonLatContributorsRequestBuilder {
        self.until = until
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool) -> CoverageLonLatContributorsRequestBuilder {
        self.disableGeojson = disableGeojson
        return self
    }
    open func withFilter(_ filter: String) -> CoverageLonLatContributorsRequestBuilder {
        self.filter = filter
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{lon};{lat}/contributors"
        path = path.replacingOccurrences(of: "{lat}", with: "\(self.lat!)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{lon}", with: "\(self.lon!)", options: .literal, range: nil)
        let URLString = "https://api.navitia.io/v1" + path
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since, 
            "until": self.until, 
            "disable_geojson": self.disableGeojson, 
            "filter": self.filter
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)

        return (url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: Contributors?,_ error: Error?) -> Void)) {
        if (self.lat == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
        }
        if (self.lon == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
        }

        Alamofire.request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<Contributors>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.lat == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
    }
    if (self.lon == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
    }

    Alamofire.request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageLonLatContributorsIdRequestBuilder: NSObject {
    let currentApi: ContributorsAPI

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel_getCoverageLonLatContributorsId: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var lat: Double? = nil
    var lon: Double? = nil
    var id: String? = nil
    var startPage: Int32? = nil
    var count: Int32? = nil
    var depth: Int32? = nil
    var forbiddenId: [String]? = nil
    var forbiddenUris: [String]? = nil
    var externalCode: String? = nil
    var headsign: String? = nil
    var showCodes: Bool? = nil
    var odtLevel: OdtLevel_getCoverageLonLatContributorsId? = nil
    var distance: Int32? = nil
    var since: String? = nil
    var until: String? = nil
    var disableGeojson: Bool? = nil

    public init(currentApi: ContributorsAPI) {
        self.currentApi = currentApi
    }

    open func withLat(_ lat: Double) -> CoverageLonLatContributorsIdRequestBuilder {
        self.lat = lat
        return self
    }
    open func withLon(_ lon: Double) -> CoverageLonLatContributorsIdRequestBuilder {
        self.lon = lon
        return self
    }
    open func withId(_ id: String) -> CoverageLonLatContributorsIdRequestBuilder {
        self.id = id
        return self
    }
    open func withStartPage(_ startPage: Int32) -> CoverageLonLatContributorsIdRequestBuilder {
        self.startPage = startPage
        return self
    }
    open func withCount(_ count: Int32) -> CoverageLonLatContributorsIdRequestBuilder {
        self.count = count
        return self
    }
    open func withDepth(_ depth: Int32) -> CoverageLonLatContributorsIdRequestBuilder {
        self.depth = depth
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]) -> CoverageLonLatContributorsIdRequestBuilder {
        self.forbiddenId = forbiddenId
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]) -> CoverageLonLatContributorsIdRequestBuilder {
        self.forbiddenUris = forbiddenUris
        return self
    }
    open func withExternalCode(_ externalCode: String) -> CoverageLonLatContributorsIdRequestBuilder {
        self.externalCode = externalCode
        return self
    }
    open func withHeadsign(_ headsign: String) -> CoverageLonLatContributorsIdRequestBuilder {
        self.headsign = headsign
        return self
    }
    open func withShowCodes(_ showCodes: Bool) -> CoverageLonLatContributorsIdRequestBuilder {
        self.showCodes = showCodes
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel_getCoverageLonLatContributorsId) -> CoverageLonLatContributorsIdRequestBuilder {
        self.odtLevel = odtLevel
        return self
    }
    open func withOdtLevel(_ odtLevelValue: String) -> CoverageLonLatContributorsIdRequestBuilder {
        return withOdtLevel(OdtLevel_getCoverageLonLatContributorsId(rawValue: odtLevelValue)!);
    }
    open func withDistance(_ distance: Int32) -> CoverageLonLatContributorsIdRequestBuilder {
        self.distance = distance
        return self
    }
    open func withSince(_ since: String) -> CoverageLonLatContributorsIdRequestBuilder {
        self.since = since
        return self
    }
    open func withUntil(_ until: String) -> CoverageLonLatContributorsIdRequestBuilder {
        self.until = until
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool) -> CoverageLonLatContributorsIdRequestBuilder {
        self.disableGeojson = disableGeojson
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{lon};{lat}/contributors/{id}"
        path = path.replacingOccurrences(of: "{lat}", with: "\(self.lat!)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{lon}", with: "\(self.lon!)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{id}", with: "\(self.id!)", options: .literal, range: nil)
        let URLString = "https://api.navitia.io/v1" + path
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since, 
            "until": self.until, 
            "disable_geojson": self.disableGeojson
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)

        return (url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: Contributors?,_ error: Error?) -> Void)) {
        if (self.lat == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
        }
        if (self.lon == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
        }
        if (self.id == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
        }

        Alamofire.request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<Contributors>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.lat == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
    }
    if (self.lon == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
    }
    if (self.id == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
    }

    Alamofire.request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageLonLatUriContributorsRequestBuilder: NSObject {
    let currentApi: ContributorsAPI

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel_getCoverageLonLatUriContributors: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var lat: Double? = nil
    var lon: Double? = nil
    var uri: String? = nil
    var startPage: Int32? = nil
    var count: Int32? = nil
    var depth: Int32? = nil
    var forbiddenId: [String]? = nil
    var forbiddenUris: [String]? = nil
    var externalCode: String? = nil
    var headsign: String? = nil
    var showCodes: Bool? = nil
    var odtLevel: OdtLevel_getCoverageLonLatUriContributors? = nil
    var distance: Int32? = nil
    var since: String? = nil
    var until: String? = nil
    var disableGeojson: Bool? = nil
    var filter: String? = nil

    public init(currentApi: ContributorsAPI) {
        self.currentApi = currentApi
    }

    open func withLat(_ lat: Double) -> CoverageLonLatUriContributorsRequestBuilder {
        self.lat = lat
        return self
    }
    open func withLon(_ lon: Double) -> CoverageLonLatUriContributorsRequestBuilder {
        self.lon = lon
        return self
    }
    open func withUri(_ uri: String) -> CoverageLonLatUriContributorsRequestBuilder {
        self.uri = uri
        return self
    }
    open func withStartPage(_ startPage: Int32) -> CoverageLonLatUriContributorsRequestBuilder {
        self.startPage = startPage
        return self
    }
    open func withCount(_ count: Int32) -> CoverageLonLatUriContributorsRequestBuilder {
        self.count = count
        return self
    }
    open func withDepth(_ depth: Int32) -> CoverageLonLatUriContributorsRequestBuilder {
        self.depth = depth
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]) -> CoverageLonLatUriContributorsRequestBuilder {
        self.forbiddenId = forbiddenId
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]) -> CoverageLonLatUriContributorsRequestBuilder {
        self.forbiddenUris = forbiddenUris
        return self
    }
    open func withExternalCode(_ externalCode: String) -> CoverageLonLatUriContributorsRequestBuilder {
        self.externalCode = externalCode
        return self
    }
    open func withHeadsign(_ headsign: String) -> CoverageLonLatUriContributorsRequestBuilder {
        self.headsign = headsign
        return self
    }
    open func withShowCodes(_ showCodes: Bool) -> CoverageLonLatUriContributorsRequestBuilder {
        self.showCodes = showCodes
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel_getCoverageLonLatUriContributors) -> CoverageLonLatUriContributorsRequestBuilder {
        self.odtLevel = odtLevel
        return self
    }
    open func withOdtLevel(_ odtLevelValue: String) -> CoverageLonLatUriContributorsRequestBuilder {
        return withOdtLevel(OdtLevel_getCoverageLonLatUriContributors(rawValue: odtLevelValue)!);
    }
    open func withDistance(_ distance: Int32) -> CoverageLonLatUriContributorsRequestBuilder {
        self.distance = distance
        return self
    }
    open func withSince(_ since: String) -> CoverageLonLatUriContributorsRequestBuilder {
        self.since = since
        return self
    }
    open func withUntil(_ until: String) -> CoverageLonLatUriContributorsRequestBuilder {
        self.until = until
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool) -> CoverageLonLatUriContributorsRequestBuilder {
        self.disableGeojson = disableGeojson
        return self
    }
    open func withFilter(_ filter: String) -> CoverageLonLatUriContributorsRequestBuilder {
        self.filter = filter
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{lon};{lat}/{uri}/contributors"
        path = path.replacingOccurrences(of: "{lat}", with: "\(self.lat!)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{lon}", with: "\(self.lon!)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{uri}", with: "\(self.uri!)", options: .literal, range: nil)
        let URLString = "https://api.navitia.io/v1" + path
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since, 
            "until": self.until, 
            "disable_geojson": self.disableGeojson, 
            "filter": self.filter
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)

        return (url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: Contributors?,_ error: Error?) -> Void)) {
        if (self.lat == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
        }
        if (self.lon == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
        }
        if (self.uri == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
        }

        Alamofire.request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<Contributors>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.lat == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
    }
    if (self.lon == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
    }
    if (self.uri == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
    }

    Alamofire.request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageLonLatUriContributorsIdRequestBuilder: NSObject {
    let currentApi: ContributorsAPI

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel_getCoverageLonLatUriContributorsId: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var lat: Double? = nil
    var lon: Double? = nil
    var uri: String? = nil
    var id: String? = nil
    var startPage: Int32? = nil
    var count: Int32? = nil
    var depth: Int32? = nil
    var forbiddenId: [String]? = nil
    var forbiddenUris: [String]? = nil
    var externalCode: String? = nil
    var headsign: String? = nil
    var showCodes: Bool? = nil
    var odtLevel: OdtLevel_getCoverageLonLatUriContributorsId? = nil
    var distance: Int32? = nil
    var since: String? = nil
    var until: String? = nil
    var disableGeojson: Bool? = nil

    public init(currentApi: ContributorsAPI) {
        self.currentApi = currentApi
    }

    open func withLat(_ lat: Double) -> CoverageLonLatUriContributorsIdRequestBuilder {
        self.lat = lat
        return self
    }
    open func withLon(_ lon: Double) -> CoverageLonLatUriContributorsIdRequestBuilder {
        self.lon = lon
        return self
    }
    open func withUri(_ uri: String) -> CoverageLonLatUriContributorsIdRequestBuilder {
        self.uri = uri
        return self
    }
    open func withId(_ id: String) -> CoverageLonLatUriContributorsIdRequestBuilder {
        self.id = id
        return self
    }
    open func withStartPage(_ startPage: Int32) -> CoverageLonLatUriContributorsIdRequestBuilder {
        self.startPage = startPage
        return self
    }
    open func withCount(_ count: Int32) -> CoverageLonLatUriContributorsIdRequestBuilder {
        self.count = count
        return self
    }
    open func withDepth(_ depth: Int32) -> CoverageLonLatUriContributorsIdRequestBuilder {
        self.depth = depth
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]) -> CoverageLonLatUriContributorsIdRequestBuilder {
        self.forbiddenId = forbiddenId
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]) -> CoverageLonLatUriContributorsIdRequestBuilder {
        self.forbiddenUris = forbiddenUris
        return self
    }
    open func withExternalCode(_ externalCode: String) -> CoverageLonLatUriContributorsIdRequestBuilder {
        self.externalCode = externalCode
        return self
    }
    open func withHeadsign(_ headsign: String) -> CoverageLonLatUriContributorsIdRequestBuilder {
        self.headsign = headsign
        return self
    }
    open func withShowCodes(_ showCodes: Bool) -> CoverageLonLatUriContributorsIdRequestBuilder {
        self.showCodes = showCodes
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel_getCoverageLonLatUriContributorsId) -> CoverageLonLatUriContributorsIdRequestBuilder {
        self.odtLevel = odtLevel
        return self
    }
    open func withOdtLevel(_ odtLevelValue: String) -> CoverageLonLatUriContributorsIdRequestBuilder {
        return withOdtLevel(OdtLevel_getCoverageLonLatUriContributorsId(rawValue: odtLevelValue)!);
    }
    open func withDistance(_ distance: Int32) -> CoverageLonLatUriContributorsIdRequestBuilder {
        self.distance = distance
        return self
    }
    open func withSince(_ since: String) -> CoverageLonLatUriContributorsIdRequestBuilder {
        self.since = since
        return self
    }
    open func withUntil(_ until: String) -> CoverageLonLatUriContributorsIdRequestBuilder {
        self.until = until
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool) -> CoverageLonLatUriContributorsIdRequestBuilder {
        self.disableGeojson = disableGeojson
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{lon};{lat}/{uri}/contributors/{id}"
        path = path.replacingOccurrences(of: "{lat}", with: "\(self.lat!)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{lon}", with: "\(self.lon!)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{uri}", with: "\(self.uri!)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{id}", with: "\(self.id!)", options: .literal, range: nil)
        let URLString = "https://api.navitia.io/v1" + path
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since, 
            "until": self.until, 
            "disable_geojson": self.disableGeojson
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)

        return (url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: Contributors?,_ error: Error?) -> Void)) {
        if (self.lat == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
        }
        if (self.lon == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
        }
        if (self.uri == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
        }
        if (self.id == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
        }

        Alamofire.request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<Contributors>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.lat == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
    }
    if (self.lon == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
    }
    if (self.uri == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
    }
    if (self.id == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
    }

    Alamofire.request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageRegionContributorsRequestBuilder: NSObject {
    let currentApi: ContributorsAPI

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel_getCoverageRegionContributors: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var region: String? = nil
    var startPage: Int32? = nil
    var count: Int32? = nil
    var depth: Int32? = nil
    var forbiddenId: [String]? = nil
    var forbiddenUris: [String]? = nil
    var externalCode: String? = nil
    var headsign: String? = nil
    var showCodes: Bool? = nil
    var odtLevel: OdtLevel_getCoverageRegionContributors? = nil
    var distance: Int32? = nil
    var since: String? = nil
    var until: String? = nil
    var disableGeojson: Bool? = nil
    var filter: String? = nil

    public init(currentApi: ContributorsAPI) {
        self.currentApi = currentApi
    }

    open func withRegion(_ region: String) -> CoverageRegionContributorsRequestBuilder {
        self.region = region
        return self
    }
    open func withStartPage(_ startPage: Int32) -> CoverageRegionContributorsRequestBuilder {
        self.startPage = startPage
        return self
    }
    open func withCount(_ count: Int32) -> CoverageRegionContributorsRequestBuilder {
        self.count = count
        return self
    }
    open func withDepth(_ depth: Int32) -> CoverageRegionContributorsRequestBuilder {
        self.depth = depth
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]) -> CoverageRegionContributorsRequestBuilder {
        self.forbiddenId = forbiddenId
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]) -> CoverageRegionContributorsRequestBuilder {
        self.forbiddenUris = forbiddenUris
        return self
    }
    open func withExternalCode(_ externalCode: String) -> CoverageRegionContributorsRequestBuilder {
        self.externalCode = externalCode
        return self
    }
    open func withHeadsign(_ headsign: String) -> CoverageRegionContributorsRequestBuilder {
        self.headsign = headsign
        return self
    }
    open func withShowCodes(_ showCodes: Bool) -> CoverageRegionContributorsRequestBuilder {
        self.showCodes = showCodes
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel_getCoverageRegionContributors) -> CoverageRegionContributorsRequestBuilder {
        self.odtLevel = odtLevel
        return self
    }
    open func withOdtLevel(_ odtLevelValue: String) -> CoverageRegionContributorsRequestBuilder {
        return withOdtLevel(OdtLevel_getCoverageRegionContributors(rawValue: odtLevelValue)!);
    }
    open func withDistance(_ distance: Int32) -> CoverageRegionContributorsRequestBuilder {
        self.distance = distance
        return self
    }
    open func withSince(_ since: String) -> CoverageRegionContributorsRequestBuilder {
        self.since = since
        return self
    }
    open func withUntil(_ until: String) -> CoverageRegionContributorsRequestBuilder {
        self.until = until
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool) -> CoverageRegionContributorsRequestBuilder {
        self.disableGeojson = disableGeojson
        return self
    }
    open func withFilter(_ filter: String) -> CoverageRegionContributorsRequestBuilder {
        self.filter = filter
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{region}/contributors"
        path = path.replacingOccurrences(of: "{region}", with: "\(self.region!)", options: .literal, range: nil)
        let URLString = "https://api.navitia.io/v1" + path
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since, 
            "until": self.until, 
            "disable_geojson": self.disableGeojson, 
            "filter": self.filter
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)

        return (url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: Contributors?,_ error: Error?) -> Void)) {
        if (self.region == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
        }

        Alamofire.request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<Contributors>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.region == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
    }

    Alamofire.request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageRegionContributorsIdRequestBuilder: NSObject {
    let currentApi: ContributorsAPI

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel_getCoverageRegionContributorsId: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var region: String? = nil
    var id: String? = nil
    var startPage: Int32? = nil
    var count: Int32? = nil
    var depth: Int32? = nil
    var forbiddenId: [String]? = nil
    var forbiddenUris: [String]? = nil
    var externalCode: String? = nil
    var headsign: String? = nil
    var showCodes: Bool? = nil
    var odtLevel: OdtLevel_getCoverageRegionContributorsId? = nil
    var distance: Int32? = nil
    var since: String? = nil
    var until: String? = nil
    var disableGeojson: Bool? = nil

    public init(currentApi: ContributorsAPI) {
        self.currentApi = currentApi
    }

    open func withRegion(_ region: String) -> CoverageRegionContributorsIdRequestBuilder {
        self.region = region
        return self
    }
    open func withId(_ id: String) -> CoverageRegionContributorsIdRequestBuilder {
        self.id = id
        return self
    }
    open func withStartPage(_ startPage: Int32) -> CoverageRegionContributorsIdRequestBuilder {
        self.startPage = startPage
        return self
    }
    open func withCount(_ count: Int32) -> CoverageRegionContributorsIdRequestBuilder {
        self.count = count
        return self
    }
    open func withDepth(_ depth: Int32) -> CoverageRegionContributorsIdRequestBuilder {
        self.depth = depth
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]) -> CoverageRegionContributorsIdRequestBuilder {
        self.forbiddenId = forbiddenId
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]) -> CoverageRegionContributorsIdRequestBuilder {
        self.forbiddenUris = forbiddenUris
        return self
    }
    open func withExternalCode(_ externalCode: String) -> CoverageRegionContributorsIdRequestBuilder {
        self.externalCode = externalCode
        return self
    }
    open func withHeadsign(_ headsign: String) -> CoverageRegionContributorsIdRequestBuilder {
        self.headsign = headsign
        return self
    }
    open func withShowCodes(_ showCodes: Bool) -> CoverageRegionContributorsIdRequestBuilder {
        self.showCodes = showCodes
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel_getCoverageRegionContributorsId) -> CoverageRegionContributorsIdRequestBuilder {
        self.odtLevel = odtLevel
        return self
    }
    open func withOdtLevel(_ odtLevelValue: String) -> CoverageRegionContributorsIdRequestBuilder {
        return withOdtLevel(OdtLevel_getCoverageRegionContributorsId(rawValue: odtLevelValue)!);
    }
    open func withDistance(_ distance: Int32) -> CoverageRegionContributorsIdRequestBuilder {
        self.distance = distance
        return self
    }
    open func withSince(_ since: String) -> CoverageRegionContributorsIdRequestBuilder {
        self.since = since
        return self
    }
    open func withUntil(_ until: String) -> CoverageRegionContributorsIdRequestBuilder {
        self.until = until
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool) -> CoverageRegionContributorsIdRequestBuilder {
        self.disableGeojson = disableGeojson
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{region}/contributors/{id}"
        path = path.replacingOccurrences(of: "{region}", with: "\(self.region!)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{id}", with: "\(self.id!)", options: .literal, range: nil)
        let URLString = "https://api.navitia.io/v1" + path
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since, 
            "until": self.until, 
            "disable_geojson": self.disableGeojson
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)

        return (url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: Contributors?,_ error: Error?) -> Void)) {
        if (self.region == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
        }
        if (self.id == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
        }

        Alamofire.request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<Contributors>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.region == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
    }
    if (self.id == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
    }

    Alamofire.request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageRegionUriContributorsRequestBuilder: NSObject {
    let currentApi: ContributorsAPI

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel_getCoverageRegionUriContributors: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var region: String? = nil
    var uri: String? = nil
    var startPage: Int32? = nil
    var count: Int32? = nil
    var depth: Int32? = nil
    var forbiddenId: [String]? = nil
    var forbiddenUris: [String]? = nil
    var externalCode: String? = nil
    var headsign: String? = nil
    var showCodes: Bool? = nil
    var odtLevel: OdtLevel_getCoverageRegionUriContributors? = nil
    var distance: Int32? = nil
    var since: String? = nil
    var until: String? = nil
    var disableGeojson: Bool? = nil
    var filter: String? = nil

    public init(currentApi: ContributorsAPI) {
        self.currentApi = currentApi
    }

    open func withRegion(_ region: String) -> CoverageRegionUriContributorsRequestBuilder {
        self.region = region
        return self
    }
    open func withUri(_ uri: String) -> CoverageRegionUriContributorsRequestBuilder {
        self.uri = uri
        return self
    }
    open func withStartPage(_ startPage: Int32) -> CoverageRegionUriContributorsRequestBuilder {
        self.startPage = startPage
        return self
    }
    open func withCount(_ count: Int32) -> CoverageRegionUriContributorsRequestBuilder {
        self.count = count
        return self
    }
    open func withDepth(_ depth: Int32) -> CoverageRegionUriContributorsRequestBuilder {
        self.depth = depth
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]) -> CoverageRegionUriContributorsRequestBuilder {
        self.forbiddenId = forbiddenId
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]) -> CoverageRegionUriContributorsRequestBuilder {
        self.forbiddenUris = forbiddenUris
        return self
    }
    open func withExternalCode(_ externalCode: String) -> CoverageRegionUriContributorsRequestBuilder {
        self.externalCode = externalCode
        return self
    }
    open func withHeadsign(_ headsign: String) -> CoverageRegionUriContributorsRequestBuilder {
        self.headsign = headsign
        return self
    }
    open func withShowCodes(_ showCodes: Bool) -> CoverageRegionUriContributorsRequestBuilder {
        self.showCodes = showCodes
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel_getCoverageRegionUriContributors) -> CoverageRegionUriContributorsRequestBuilder {
        self.odtLevel = odtLevel
        return self
    }
    open func withOdtLevel(_ odtLevelValue: String) -> CoverageRegionUriContributorsRequestBuilder {
        return withOdtLevel(OdtLevel_getCoverageRegionUriContributors(rawValue: odtLevelValue)!);
    }
    open func withDistance(_ distance: Int32) -> CoverageRegionUriContributorsRequestBuilder {
        self.distance = distance
        return self
    }
    open func withSince(_ since: String) -> CoverageRegionUriContributorsRequestBuilder {
        self.since = since
        return self
    }
    open func withUntil(_ until: String) -> CoverageRegionUriContributorsRequestBuilder {
        self.until = until
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool) -> CoverageRegionUriContributorsRequestBuilder {
        self.disableGeojson = disableGeojson
        return self
    }
    open func withFilter(_ filter: String) -> CoverageRegionUriContributorsRequestBuilder {
        self.filter = filter
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{region}/{uri}/contributors"
        path = path.replacingOccurrences(of: "{region}", with: "\(self.region!)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{uri}", with: "\(self.uri!)", options: .literal, range: nil)
        let URLString = "https://api.navitia.io/v1" + path
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since, 
            "until": self.until, 
            "disable_geojson": self.disableGeojson, 
            "filter": self.filter
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)

        return (url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: Contributors?,_ error: Error?) -> Void)) {
        if (self.region == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
        }
        if (self.uri == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
        }

        Alamofire.request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<Contributors>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.region == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
    }
    if (self.uri == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
    }

    Alamofire.request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

open class CoverageRegionUriContributorsIdRequestBuilder: NSObject {
    let currentApi: ContributorsAPI

    /**
    * enum for parameter odtLevel
    */
    public enum OdtLevel_getCoverageRegionUriContributorsId: String { 
        case scheduled = "scheduled"
        case all = "all"
        case zonal = "zonal"
        case withStops = "with_stops"
    }
    var region: String? = nil
    var uri: String? = nil
    var id: String? = nil
    var startPage: Int32? = nil
    var count: Int32? = nil
    var depth: Int32? = nil
    var forbiddenId: [String]? = nil
    var forbiddenUris: [String]? = nil
    var externalCode: String? = nil
    var headsign: String? = nil
    var showCodes: Bool? = nil
    var odtLevel: OdtLevel_getCoverageRegionUriContributorsId? = nil
    var distance: Int32? = nil
    var since: String? = nil
    var until: String? = nil
    var disableGeojson: Bool? = nil

    public init(currentApi: ContributorsAPI) {
        self.currentApi = currentApi
    }

    open func withRegion(_ region: String) -> CoverageRegionUriContributorsIdRequestBuilder {
        self.region = region
        return self
    }
    open func withUri(_ uri: String) -> CoverageRegionUriContributorsIdRequestBuilder {
        self.uri = uri
        return self
    }
    open func withId(_ id: String) -> CoverageRegionUriContributorsIdRequestBuilder {
        self.id = id
        return self
    }
    open func withStartPage(_ startPage: Int32) -> CoverageRegionUriContributorsIdRequestBuilder {
        self.startPage = startPage
        return self
    }
    open func withCount(_ count: Int32) -> CoverageRegionUriContributorsIdRequestBuilder {
        self.count = count
        return self
    }
    open func withDepth(_ depth: Int32) -> CoverageRegionUriContributorsIdRequestBuilder {
        self.depth = depth
        return self
    }
    open func withForbiddenId(_ forbiddenId: [String]) -> CoverageRegionUriContributorsIdRequestBuilder {
        self.forbiddenId = forbiddenId
        return self
    }
    open func withForbiddenUris(_ forbiddenUris: [String]) -> CoverageRegionUriContributorsIdRequestBuilder {
        self.forbiddenUris = forbiddenUris
        return self
    }
    open func withExternalCode(_ externalCode: String) -> CoverageRegionUriContributorsIdRequestBuilder {
        self.externalCode = externalCode
        return self
    }
    open func withHeadsign(_ headsign: String) -> CoverageRegionUriContributorsIdRequestBuilder {
        self.headsign = headsign
        return self
    }
    open func withShowCodes(_ showCodes: Bool) -> CoverageRegionUriContributorsIdRequestBuilder {
        self.showCodes = showCodes
        return self
    }
    open func withOdtLevel(_ odtLevel: OdtLevel_getCoverageRegionUriContributorsId) -> CoverageRegionUriContributorsIdRequestBuilder {
        self.odtLevel = odtLevel
        return self
    }
    open func withOdtLevel(_ odtLevelValue: String) -> CoverageRegionUriContributorsIdRequestBuilder {
        return withOdtLevel(OdtLevel_getCoverageRegionUriContributorsId(rawValue: odtLevelValue)!);
    }
    open func withDistance(_ distance: Int32) -> CoverageRegionUriContributorsIdRequestBuilder {
        self.distance = distance
        return self
    }
    open func withSince(_ since: String) -> CoverageRegionUriContributorsIdRequestBuilder {
        self.since = since
        return self
    }
    open func withUntil(_ until: String) -> CoverageRegionUriContributorsIdRequestBuilder {
        self.until = until
        return self
    }
    open func withDisableGeojson(_ disableGeojson: Bool) -> CoverageRegionUriContributorsIdRequestBuilder {
        self.disableGeojson = disableGeojson
        return self
    }

    open func makeUrl() -> String {
        var path = "/coverage/{region}/{uri}/contributors/{id}"
        path = path.replacingOccurrences(of: "{region}", with: "\(self.region!)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{uri}", with: "\(self.uri!)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{id}", with: "\(self.id!)", options: .literal, range: nil)
        let URLString = "https://api.navitia.io/v1" + path
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "start_page": self.startPage?.encodeToJSON(), 
            "count": self.count?.encodeToJSON(), 
            "depth": self.depth?.encodeToJSON(), 
            "forbidden_id[]": self.forbiddenId, 
            "forbidden_uris[]": self.forbiddenUris, 
            "external_code": self.externalCode, 
            "headsign": self.headsign, 
            "show_codes": self.showCodes, 
            "odt_level": self.odtLevel?.rawValue, 
            "distance": self.distance?.encodeToJSON(), 
            "since": self.since, 
            "until": self.until, 
            "disable_geojson": self.disableGeojson
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)

        return (url?.string ?? URLString)
    }

    open func get(completion: @escaping ((_ data: Contributors?,_ error: Error?) -> Void)) {
        if (self.region == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
        }
        if (self.uri == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
        }
        if (self.id == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
        }

        Alamofire.request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<Contributors>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    open func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.region == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
    }
    if (self.uri == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : uri"])))
    }
    if (self.id == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : id"])))
    }

    Alamofire.request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}



open class ContributorsAPI: APIBase {
    let token: String

    public init(token: String) {
        self.token = token
    }

    public func newCoverageLonLatContributorsRequestBuilder() -> CoverageLonLatContributorsRequestBuilder {
        return CoverageLonLatContributorsRequestBuilder(currentApi: self)
    }
    public func newCoverageLonLatContributorsIdRequestBuilder() -> CoverageLonLatContributorsIdRequestBuilder {
        return CoverageLonLatContributorsIdRequestBuilder(currentApi: self)
    }
    public func newCoverageLonLatUriContributorsRequestBuilder() -> CoverageLonLatUriContributorsRequestBuilder {
        return CoverageLonLatUriContributorsRequestBuilder(currentApi: self)
    }
    public func newCoverageLonLatUriContributorsIdRequestBuilder() -> CoverageLonLatUriContributorsIdRequestBuilder {
        return CoverageLonLatUriContributorsIdRequestBuilder(currentApi: self)
    }
    public func newCoverageRegionContributorsRequestBuilder() -> CoverageRegionContributorsRequestBuilder {
        return CoverageRegionContributorsRequestBuilder(currentApi: self)
    }
    public func newCoverageRegionContributorsIdRequestBuilder() -> CoverageRegionContributorsIdRequestBuilder {
        return CoverageRegionContributorsIdRequestBuilder(currentApi: self)
    }
    public func newCoverageRegionUriContributorsRequestBuilder() -> CoverageRegionUriContributorsRequestBuilder {
        return CoverageRegionUriContributorsRequestBuilder(currentApi: self)
    }
    public func newCoverageRegionUriContributorsIdRequestBuilder() -> CoverageRegionUriContributorsIdRequestBuilder {
        return CoverageRegionUriContributorsIdRequestBuilder(currentApi: self)
    }
}
