//
// GraphicalIsochroneApi.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class CoverageLonLatIsochronesRequestBuilder: NSObject {
    let currentApi: GraphicalIsochroneApi

    /**
    * enum for parameter datetimeRepresents
    */
    public enum DatetimeRepresents: String { 
        case arrival = "arrival"
        case departure = "departure"
    }
    /**
    * enum for parameter firstSectionMode
    */
    public enum FirstSectionMode: String { 
        case taxi = "taxi"
        case walking = "walking"
        case car = "car"
        case ridesharing = "ridesharing"
        case bss = "bss"
        case bike = "bike"
    }
    /**
    * enum for parameter lastSectionMode
    */
    public enum LastSectionMode: String { 
        case taxi = "taxi"
        case walking = "walking"
        case car = "car"
        case ridesharing = "ridesharing"
        case bss = "bss"
        case bike = "bike"
    }
    /**
    * enum for parameter dataFreshness
    */
    public enum DataFreshness: String { 
        case baseSchedule = "base_schedule"
        case adaptedSchedule = "adapted_schedule"
        case realtime = "realtime"
    }
    /**
    * enum for parameter travelerType
    */
    public enum TravelerType: String { 
        case cyclist = "cyclist"
        case luggage = "luggage"
        case wheelchair = "wheelchair"
        case standard = "standard"
        case motorist = "motorist"
        case fastWalker = "fast_walker"
        case slowWalker = "slow_walker"
    }
    /**
    * enum for parameter directPath
    */
    public enum DirectPath: String { 
        case indifferent = "indifferent"
        case only = "only"
        case _none = "none"
    }
    /**
    * enum for parameter directPathMode
    */
    public enum DirectPathMode: String { 
        case taxi = "taxi"
        case walking = "walking"
        case car = "car"
        case ridesharing = "ridesharing"
        case bss = "bss"
        case bike = "bike"
    }
    var lat:Double? = nil
    var lon:Double? = nil
    var from:String? = nil
    var to:String? = nil
    var datetime:Date? = nil
    var datetimeRepresents: DatetimeRepresents? = nil
    var maxNbTransfers:Int32? = nil
    var minNbTransfers:Int32? = nil
    var firstSectionMode: [String]? = nil
    var lastSectionMode: [String]? = nil
    var maxDurationToPt:Int32? = nil
    var maxWalkingDurationToPt:Int32? = nil
    var maxBikeDurationToPt:Int32? = nil
    var maxBssDurationToPt:Int32? = nil
    var maxCarDurationToPt:Int32? = nil
    var maxRidesharingDurationToPt:Int32? = nil
    var walkingSpeed:Float? = nil
    var bikeSpeed:Float? = nil
    var bssSpeed:Float? = nil
    var carSpeed:Float? = nil
    var ridesharingSpeed:Float? = nil
    var taxiSpeed:Float? = nil
    var forbiddenUris:[String]? = nil
    var allowedId:[String]? = nil
    var disruptionActive:Bool? = nil
    var dataFreshness: DataFreshness? = nil
    var maxDuration:Int32? = nil
    var wheelchair:Bool? = nil
    var travelerType: TravelerType? = nil
    var directPath: DirectPath? = nil
    var freeRadiusFrom:Int32? = nil
    var freeRadiusTo:Int32? = nil
    var directPathMode: [String]? = nil
    var minDuration:Int32? = nil
    var boundaryDuration:[Int32]? = nil
    var debugURL: String? = nil

    public init(currentApi: GraphicalIsochroneApi) {
        self.currentApi = currentApi
    }

    public func withLat(_ lat: Double?) -> CoverageLonLatIsochronesRequestBuilder {
        self.lat = lat
        
        return self
    }
    public func withLon(_ lon: Double?) -> CoverageLonLatIsochronesRequestBuilder {
        self.lon = lon
        
        return self
    }
    public func withFrom(_ from: String?) -> CoverageLonLatIsochronesRequestBuilder {
        self.from = from
        
        return self
    }
    public func withTo(_ to: String?) -> CoverageLonLatIsochronesRequestBuilder {
        self.to = to
        
        return self
    }
    public func withDatetime(_ datetime: Date?) -> CoverageLonLatIsochronesRequestBuilder {
        self.datetime = datetime
        
        return self
    }
    public func withDatetimeRepresents(_ datetimeRepresents: DatetimeRepresents?) -> CoverageLonLatIsochronesRequestBuilder {
        self.datetimeRepresents = datetimeRepresents

        return self
    }
    public func withMaxNbTransfers(_ maxNbTransfers: Int32?) -> CoverageLonLatIsochronesRequestBuilder {
        self.maxNbTransfers = maxNbTransfers
        
        return self
    }
    public func withMinNbTransfers(_ minNbTransfers: Int32?) -> CoverageLonLatIsochronesRequestBuilder {
        self.minNbTransfers = minNbTransfers
        
        return self
    }
    public func withFirstSectionMode(_ firstSectionMode: [FirstSectionMode]?) -> CoverageLonLatIsochronesRequestBuilder {
        guard let firstSectionMode = firstSectionMode else {
            return self
        }
        
        var items = [String]()
        for item in firstSectionMode {
            items.append(item.rawValue)
        }
        self.firstSectionMode = items

        return self
    }
    public func withLastSectionMode(_ lastSectionMode: [LastSectionMode]?) -> CoverageLonLatIsochronesRequestBuilder {
        guard let lastSectionMode = lastSectionMode else {
            return self
        }
        
        var items = [String]()
        for item in lastSectionMode {
            items.append(item.rawValue)
        }
        self.lastSectionMode = items

        return self
    }
    public func withMaxDurationToPt(_ maxDurationToPt: Int32?) -> CoverageLonLatIsochronesRequestBuilder {
        self.maxDurationToPt = maxDurationToPt
        
        return self
    }
    public func withMaxWalkingDurationToPt(_ maxWalkingDurationToPt: Int32?) -> CoverageLonLatIsochronesRequestBuilder {
        self.maxWalkingDurationToPt = maxWalkingDurationToPt
        
        return self
    }
    public func withMaxBikeDurationToPt(_ maxBikeDurationToPt: Int32?) -> CoverageLonLatIsochronesRequestBuilder {
        self.maxBikeDurationToPt = maxBikeDurationToPt
        
        return self
    }
    public func withMaxBssDurationToPt(_ maxBssDurationToPt: Int32?) -> CoverageLonLatIsochronesRequestBuilder {
        self.maxBssDurationToPt = maxBssDurationToPt
        
        return self
    }
    public func withMaxCarDurationToPt(_ maxCarDurationToPt: Int32?) -> CoverageLonLatIsochronesRequestBuilder {
        self.maxCarDurationToPt = maxCarDurationToPt
        
        return self
    }
    public func withMaxRidesharingDurationToPt(_ maxRidesharingDurationToPt: Int32?) -> CoverageLonLatIsochronesRequestBuilder {
        self.maxRidesharingDurationToPt = maxRidesharingDurationToPt
        
        return self
    }
    public func withWalkingSpeed(_ walkingSpeed: Float?) -> CoverageLonLatIsochronesRequestBuilder {
        self.walkingSpeed = walkingSpeed
        
        return self
    }
    public func withBikeSpeed(_ bikeSpeed: Float?) -> CoverageLonLatIsochronesRequestBuilder {
        self.bikeSpeed = bikeSpeed
        
        return self
    }
    public func withBssSpeed(_ bssSpeed: Float?) -> CoverageLonLatIsochronesRequestBuilder {
        self.bssSpeed = bssSpeed
        
        return self
    }
    public func withCarSpeed(_ carSpeed: Float?) -> CoverageLonLatIsochronesRequestBuilder {
        self.carSpeed = carSpeed
        
        return self
    }
    public func withRidesharingSpeed(_ ridesharingSpeed: Float?) -> CoverageLonLatIsochronesRequestBuilder {
        self.ridesharingSpeed = ridesharingSpeed
        
        return self
    }
    public func withTaxiSpeed(_ taxiSpeed: Float?) -> CoverageLonLatIsochronesRequestBuilder {
        self.taxiSpeed = taxiSpeed
        
        return self
    }
    public func withForbiddenUris(_ forbiddenUris: [String]?) -> CoverageLonLatIsochronesRequestBuilder {
        self.forbiddenUris = forbiddenUris
        
        return self
    }
    public func withAllowedId(_ allowedId: [String]?) -> CoverageLonLatIsochronesRequestBuilder {
        self.allowedId = allowedId
        
        return self
    }
    public func withDisruptionActive(_ disruptionActive: Bool?) -> CoverageLonLatIsochronesRequestBuilder {
        self.disruptionActive = disruptionActive
        
        return self
    }
    public func withDataFreshness(_ dataFreshness: DataFreshness?) -> CoverageLonLatIsochronesRequestBuilder {
        self.dataFreshness = dataFreshness

        return self
    }
    public func withMaxDuration(_ maxDuration: Int32?) -> CoverageLonLatIsochronesRequestBuilder {
        self.maxDuration = maxDuration
        
        return self
    }
    public func withWheelchair(_ wheelchair: Bool?) -> CoverageLonLatIsochronesRequestBuilder {
        self.wheelchair = wheelchair
        
        return self
    }
    public func withTravelerType(_ travelerType: TravelerType?) -> CoverageLonLatIsochronesRequestBuilder {
        self.travelerType = travelerType

        return self
    }
    public func withDirectPath(_ directPath: DirectPath?) -> CoverageLonLatIsochronesRequestBuilder {
        self.directPath = directPath

        return self
    }
    public func withFreeRadiusFrom(_ freeRadiusFrom: Int32?) -> CoverageLonLatIsochronesRequestBuilder {
        self.freeRadiusFrom = freeRadiusFrom
        
        return self
    }
    public func withFreeRadiusTo(_ freeRadiusTo: Int32?) -> CoverageLonLatIsochronesRequestBuilder {
        self.freeRadiusTo = freeRadiusTo
        
        return self
    }
    public func withDirectPathMode(_ directPathMode: [DirectPathMode]?) -> CoverageLonLatIsochronesRequestBuilder {
        guard let directPathMode = directPathMode else {
            return self
        }
        
        var items = [String]()
        for item in directPathMode {
            items.append(item.rawValue)
        }
        self.directPathMode = items

        return self
    }
    public func withMinDuration(_ minDuration: Int32?) -> CoverageLonLatIsochronesRequestBuilder {
        self.minDuration = minDuration
        
        return self
    }
    public func withBoundaryDuration(_ boundaryDuration: [Int32]?) -> CoverageLonLatIsochronesRequestBuilder {
        self.boundaryDuration = boundaryDuration
        
        return self
    }



    public func withDebugURL(_ debugURL: String?) -> CoverageLonLatIsochronesRequestBuilder {
        self.debugURL = debugURL
        return self
    }

    public func makeUrl() -> String {
        var path = "/coverage/{lon};{lat}/isochrones"

        if let lat = lat {
            let latPreEscape: String = "\(lat)"
            let latPostEscape: String = latPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{lat}", with: latPostEscape, options: .literal, range: nil)
        }

        if let lon = lon {
            let lonPreEscape: String = "\(lon)"
            let lonPostEscape: String = lonPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{lon}", with: lonPostEscape, options: .literal, range: nil)
        }

        let URLString = String(format: "%@%@", NavitiaSDKAPI.basePath, path)
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "from": self.from, 
            "to": self.to, 
            "datetime": self.datetime?.encodeToJSON(), 
            "datetime_represents": self.datetimeRepresents?.rawValue, 
            "max_nb_transfers": self.maxNbTransfers?.encodeToJSON(), 
            "min_nb_transfers": self.minNbTransfers?.encodeToJSON(), 
            "first_section_mode[]": self.firstSectionMode, 
            "last_section_mode[]": self.lastSectionMode, 
            "max_duration_to_pt": self.maxDurationToPt?.encodeToJSON(), 
            "max_walking_duration_to_pt": self.maxWalkingDurationToPt?.encodeToJSON(), 
            "max_bike_duration_to_pt": self.maxBikeDurationToPt?.encodeToJSON(), 
            "max_bss_duration_to_pt": self.maxBssDurationToPt?.encodeToJSON(), 
            "max_car_duration_to_pt": self.maxCarDurationToPt?.encodeToJSON(), 
            "max_ridesharing_duration_to_pt": self.maxRidesharingDurationToPt?.encodeToJSON(), 
            "walking_speed": self.walkingSpeed, 
            "bike_speed": self.bikeSpeed, 
            "bss_speed": self.bssSpeed, 
            "car_speed": self.carSpeed, 
            "ridesharing_speed": self.ridesharingSpeed, 
            "taxi_speed": self.taxiSpeed, 
            "forbidden_uris[]": self.forbiddenUris, 
            "allowed_id[]": self.allowedId, 
            "disruption_active": self.disruptionActive, 
            "data_freshness": self.dataFreshness?.rawValue, 
            "max_duration": self.maxDuration?.encodeToJSON(), 
            "wheelchair": self.wheelchair, 
            "traveler_type": self.travelerType?.rawValue, 
            "direct_path": self.directPath?.rawValue, 
            "free_radius_from": self.freeRadiusFrom?.encodeToJSON(), 
            "free_radius_to": self.freeRadiusTo?.encodeToJSON(), 
            "direct_path_mode[]": self.directPathMode, 
            "min_duration": self.minDuration?.encodeToJSON(), 
            "boundary_duration[]": self.boundaryDuration
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (debugURL ?? url?.string ?? URLString)
    }

    public func get(completion: @escaping ((_ data: GraphicalIsrochone1?,_ error: Error?) -> Void)) {
        if (self.lat == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
        }
        if (self.lon == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<GraphicalIsrochone1>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    public func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.lat == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lat"])))
    }
    if (self.lon == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : lon"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}

public class CoverageRegionIsochronesRequestBuilder: NSObject {
    let currentApi: GraphicalIsochroneApi

    /**
    * enum for parameter datetimeRepresents
    */
    public enum DatetimeRepresents: String { 
        case arrival = "arrival"
        case departure = "departure"
    }
    /**
    * enum for parameter firstSectionMode
    */
    public enum FirstSectionMode: String { 
        case taxi = "taxi"
        case walking = "walking"
        case car = "car"
        case ridesharing = "ridesharing"
        case bss = "bss"
        case bike = "bike"
    }
    /**
    * enum for parameter lastSectionMode
    */
    public enum LastSectionMode: String { 
        case taxi = "taxi"
        case walking = "walking"
        case car = "car"
        case ridesharing = "ridesharing"
        case bss = "bss"
        case bike = "bike"
    }
    /**
    * enum for parameter dataFreshness
    */
    public enum DataFreshness: String { 
        case baseSchedule = "base_schedule"
        case adaptedSchedule = "adapted_schedule"
        case realtime = "realtime"
    }
    /**
    * enum for parameter travelerType
    */
    public enum TravelerType: String { 
        case cyclist = "cyclist"
        case luggage = "luggage"
        case wheelchair = "wheelchair"
        case standard = "standard"
        case motorist = "motorist"
        case fastWalker = "fast_walker"
        case slowWalker = "slow_walker"
    }
    /**
    * enum for parameter directPath
    */
    public enum DirectPath: String { 
        case indifferent = "indifferent"
        case only = "only"
        case _none = "none"
    }
    /**
    * enum for parameter directPathMode
    */
    public enum DirectPathMode: String { 
        case taxi = "taxi"
        case walking = "walking"
        case car = "car"
        case ridesharing = "ridesharing"
        case bss = "bss"
        case bike = "bike"
    }
    var region:String? = nil
    var from:String? = nil
    var to:String? = nil
    var datetime:Date? = nil
    var datetimeRepresents: DatetimeRepresents? = nil
    var maxNbTransfers:Int32? = nil
    var minNbTransfers:Int32? = nil
    var firstSectionMode: [String]? = nil
    var lastSectionMode: [String]? = nil
    var maxDurationToPt:Int32? = nil
    var maxWalkingDurationToPt:Int32? = nil
    var maxBikeDurationToPt:Int32? = nil
    var maxBssDurationToPt:Int32? = nil
    var maxCarDurationToPt:Int32? = nil
    var maxRidesharingDurationToPt:Int32? = nil
    var walkingSpeed:Float? = nil
    var bikeSpeed:Float? = nil
    var bssSpeed:Float? = nil
    var carSpeed:Float? = nil
    var ridesharingSpeed:Float? = nil
    var taxiSpeed:Float? = nil
    var forbiddenUris:[String]? = nil
    var allowedId:[String]? = nil
    var disruptionActive:Bool? = nil
    var dataFreshness: DataFreshness? = nil
    var maxDuration:Int32? = nil
    var wheelchair:Bool? = nil
    var travelerType: TravelerType? = nil
    var directPath: DirectPath? = nil
    var freeRadiusFrom:Int32? = nil
    var freeRadiusTo:Int32? = nil
    var directPathMode: [String]? = nil
    var minDuration:Int32? = nil
    var boundaryDuration:[Int32]? = nil
    var debugURL: String? = nil

    public init(currentApi: GraphicalIsochroneApi) {
        self.currentApi = currentApi
    }

    public func withRegion(_ region: String?) -> CoverageRegionIsochronesRequestBuilder {
        self.region = region
        
        return self
    }
    public func withFrom(_ from: String?) -> CoverageRegionIsochronesRequestBuilder {
        self.from = from
        
        return self
    }
    public func withTo(_ to: String?) -> CoverageRegionIsochronesRequestBuilder {
        self.to = to
        
        return self
    }
    public func withDatetime(_ datetime: Date?) -> CoverageRegionIsochronesRequestBuilder {
        self.datetime = datetime
        
        return self
    }
    public func withDatetimeRepresents(_ datetimeRepresents: DatetimeRepresents?) -> CoverageRegionIsochronesRequestBuilder {
        self.datetimeRepresents = datetimeRepresents

        return self
    }
    public func withMaxNbTransfers(_ maxNbTransfers: Int32?) -> CoverageRegionIsochronesRequestBuilder {
        self.maxNbTransfers = maxNbTransfers
        
        return self
    }
    public func withMinNbTransfers(_ minNbTransfers: Int32?) -> CoverageRegionIsochronesRequestBuilder {
        self.minNbTransfers = minNbTransfers
        
        return self
    }
    public func withFirstSectionMode(_ firstSectionMode: [FirstSectionMode]?) -> CoverageRegionIsochronesRequestBuilder {
        guard let firstSectionMode = firstSectionMode else {
            return self
        }
        
        var items = [String]()
        for item in firstSectionMode {
            items.append(item.rawValue)
        }
        self.firstSectionMode = items

        return self
    }
    public func withLastSectionMode(_ lastSectionMode: [LastSectionMode]?) -> CoverageRegionIsochronesRequestBuilder {
        guard let lastSectionMode = lastSectionMode else {
            return self
        }
        
        var items = [String]()
        for item in lastSectionMode {
            items.append(item.rawValue)
        }
        self.lastSectionMode = items

        return self
    }
    public func withMaxDurationToPt(_ maxDurationToPt: Int32?) -> CoverageRegionIsochronesRequestBuilder {
        self.maxDurationToPt = maxDurationToPt
        
        return self
    }
    public func withMaxWalkingDurationToPt(_ maxWalkingDurationToPt: Int32?) -> CoverageRegionIsochronesRequestBuilder {
        self.maxWalkingDurationToPt = maxWalkingDurationToPt
        
        return self
    }
    public func withMaxBikeDurationToPt(_ maxBikeDurationToPt: Int32?) -> CoverageRegionIsochronesRequestBuilder {
        self.maxBikeDurationToPt = maxBikeDurationToPt
        
        return self
    }
    public func withMaxBssDurationToPt(_ maxBssDurationToPt: Int32?) -> CoverageRegionIsochronesRequestBuilder {
        self.maxBssDurationToPt = maxBssDurationToPt
        
        return self
    }
    public func withMaxCarDurationToPt(_ maxCarDurationToPt: Int32?) -> CoverageRegionIsochronesRequestBuilder {
        self.maxCarDurationToPt = maxCarDurationToPt
        
        return self
    }
    public func withMaxRidesharingDurationToPt(_ maxRidesharingDurationToPt: Int32?) -> CoverageRegionIsochronesRequestBuilder {
        self.maxRidesharingDurationToPt = maxRidesharingDurationToPt
        
        return self
    }
    public func withWalkingSpeed(_ walkingSpeed: Float?) -> CoverageRegionIsochronesRequestBuilder {
        self.walkingSpeed = walkingSpeed
        
        return self
    }
    public func withBikeSpeed(_ bikeSpeed: Float?) -> CoverageRegionIsochronesRequestBuilder {
        self.bikeSpeed = bikeSpeed
        
        return self
    }
    public func withBssSpeed(_ bssSpeed: Float?) -> CoverageRegionIsochronesRequestBuilder {
        self.bssSpeed = bssSpeed
        
        return self
    }
    public func withCarSpeed(_ carSpeed: Float?) -> CoverageRegionIsochronesRequestBuilder {
        self.carSpeed = carSpeed
        
        return self
    }
    public func withRidesharingSpeed(_ ridesharingSpeed: Float?) -> CoverageRegionIsochronesRequestBuilder {
        self.ridesharingSpeed = ridesharingSpeed
        
        return self
    }
    public func withTaxiSpeed(_ taxiSpeed: Float?) -> CoverageRegionIsochronesRequestBuilder {
        self.taxiSpeed = taxiSpeed
        
        return self
    }
    public func withForbiddenUris(_ forbiddenUris: [String]?) -> CoverageRegionIsochronesRequestBuilder {
        self.forbiddenUris = forbiddenUris
        
        return self
    }
    public func withAllowedId(_ allowedId: [String]?) -> CoverageRegionIsochronesRequestBuilder {
        self.allowedId = allowedId
        
        return self
    }
    public func withDisruptionActive(_ disruptionActive: Bool?) -> CoverageRegionIsochronesRequestBuilder {
        self.disruptionActive = disruptionActive
        
        return self
    }
    public func withDataFreshness(_ dataFreshness: DataFreshness?) -> CoverageRegionIsochronesRequestBuilder {
        self.dataFreshness = dataFreshness

        return self
    }
    public func withMaxDuration(_ maxDuration: Int32?) -> CoverageRegionIsochronesRequestBuilder {
        self.maxDuration = maxDuration
        
        return self
    }
    public func withWheelchair(_ wheelchair: Bool?) -> CoverageRegionIsochronesRequestBuilder {
        self.wheelchair = wheelchair
        
        return self
    }
    public func withTravelerType(_ travelerType: TravelerType?) -> CoverageRegionIsochronesRequestBuilder {
        self.travelerType = travelerType

        return self
    }
    public func withDirectPath(_ directPath: DirectPath?) -> CoverageRegionIsochronesRequestBuilder {
        self.directPath = directPath

        return self
    }
    public func withFreeRadiusFrom(_ freeRadiusFrom: Int32?) -> CoverageRegionIsochronesRequestBuilder {
        self.freeRadiusFrom = freeRadiusFrom
        
        return self
    }
    public func withFreeRadiusTo(_ freeRadiusTo: Int32?) -> CoverageRegionIsochronesRequestBuilder {
        self.freeRadiusTo = freeRadiusTo
        
        return self
    }
    public func withDirectPathMode(_ directPathMode: [DirectPathMode]?) -> CoverageRegionIsochronesRequestBuilder {
        guard let directPathMode = directPathMode else {
            return self
        }
        
        var items = [String]()
        for item in directPathMode {
            items.append(item.rawValue)
        }
        self.directPathMode = items

        return self
    }
    public func withMinDuration(_ minDuration: Int32?) -> CoverageRegionIsochronesRequestBuilder {
        self.minDuration = minDuration
        
        return self
    }
    public func withBoundaryDuration(_ boundaryDuration: [Int32]?) -> CoverageRegionIsochronesRequestBuilder {
        self.boundaryDuration = boundaryDuration
        
        return self
    }



    public func withDebugURL(_ debugURL: String?) -> CoverageRegionIsochronesRequestBuilder {
        self.debugURL = debugURL
        return self
    }

    public func makeUrl() -> String {
        var path = "/coverage/{region}/isochrones"

        if let region = region {
            let regionPreEscape: String = "\(region)"
            let regionPostEscape: String = regionPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            path = path.replacingOccurrences(of: "{region}", with: regionPostEscape, options: .literal, range: nil)
        }

        let URLString = String(format: "%@%@", NavitiaSDKAPI.basePath, path)
        let url = NSURLComponents(string: URLString)

        let paramValues: [String: Any?] = [
            "from": self.from, 
            "to": self.to, 
            "datetime": self.datetime?.encodeToJSON(), 
            "datetime_represents": self.datetimeRepresents?.rawValue, 
            "max_nb_transfers": self.maxNbTransfers?.encodeToJSON(), 
            "min_nb_transfers": self.minNbTransfers?.encodeToJSON(), 
            "first_section_mode[]": self.firstSectionMode, 
            "last_section_mode[]": self.lastSectionMode, 
            "max_duration_to_pt": self.maxDurationToPt?.encodeToJSON(), 
            "max_walking_duration_to_pt": self.maxWalkingDurationToPt?.encodeToJSON(), 
            "max_bike_duration_to_pt": self.maxBikeDurationToPt?.encodeToJSON(), 
            "max_bss_duration_to_pt": self.maxBssDurationToPt?.encodeToJSON(), 
            "max_car_duration_to_pt": self.maxCarDurationToPt?.encodeToJSON(), 
            "max_ridesharing_duration_to_pt": self.maxRidesharingDurationToPt?.encodeToJSON(), 
            "walking_speed": self.walkingSpeed, 
            "bike_speed": self.bikeSpeed, 
            "bss_speed": self.bssSpeed, 
            "car_speed": self.carSpeed, 
            "ridesharing_speed": self.ridesharingSpeed, 
            "taxi_speed": self.taxiSpeed, 
            "forbidden_uris[]": self.forbiddenUris, 
            "allowed_id[]": self.allowedId, 
            "disruption_active": self.disruptionActive, 
            "data_freshness": self.dataFreshness?.rawValue, 
            "max_duration": self.maxDuration?.encodeToJSON(), 
            "wheelchair": self.wheelchair, 
            "traveler_type": self.travelerType?.rawValue, 
            "direct_path": self.directPath?.rawValue, 
            "free_radius_from": self.freeRadiusFrom?.encodeToJSON(), 
            "free_radius_to": self.freeRadiusTo?.encodeToJSON(), 
            "direct_path_mode[]": self.directPathMode, 
            "min_duration": self.minDuration?.encodeToJSON(), 
            "boundary_duration[]": self.boundaryDuration
        ]
        url?.queryItems = APIHelper.mapValuesToQueryItems(values: paramValues)
        url?.percentEncodedQuery = url?.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")

        return (debugURL ?? url?.string ?? URLString)
    }

    public func get(completion: @escaping ((_ data: GraphicalIsrochone1?,_ error: Error?) -> Void)) {
        if (self.region == nil) {
            completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
        }

        request(self.makeUrl())
            .authenticate(user: currentApi.token, password: "")
            .validate()
            .responseObject{ (response: (DataResponse<GraphicalIsrochone1>)) in
                switch response.result {
                case .success:
                    completion(response.result.value, nil)
                case .failure(let error):
                    completion(nil, error)
                }
            }
    }

    public func rawGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
    if (self.region == nil) {
        completion(nil, ErrorResponse.Error(500, nil, NSError(domain: "localhost", code: 500, userInfo: ["reason": "Missing mandatory argument : region"])))
    }

    request(self.makeUrl())
        .authenticate(user: currentApi.token, password: "")
        .validate()
        .responseString{ (response: (DataResponse<String>)) in
            switch response.result {
            case .success:
                completion(response.result.value, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}



public class GraphicalIsochroneApi: APIBase {
    let token: String

    public init(token: String) {
        self.token = token
    }

    public func newCoverageLonLatIsochronesRequestBuilder() -> CoverageLonLatIsochronesRequestBuilder {
        return CoverageLonLatIsochronesRequestBuilder(currentApi: self)
    }
    public func newCoverageRegionIsochronesRequestBuilder() -> CoverageRegionIsochronesRequestBuilder {
        return CoverageRegionIsochronesRequestBuilder(currentApi: self)
    }
}
