//
// Arrivals.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Arrivals: Codable {

    public var pagination: Pagination
    public var links: [LinkSchema]?
    public var disruptions: [Disruption]
    public var notes: [Note]?
    public var arrivals: [Passage]
    public var feedPublishers: [FeedPublisher]
    public var context: Context?
    public var error: ModelError?
    public var exceptions: [Exception]?

    public init(pagination: Pagination, links: [LinkSchema]?, disruptions: [Disruption], notes: [Note]?, arrivals: [Passage], feedPublishers: [FeedPublisher], context: Context?, error: ModelError?, exceptions: [Exception]?) {
        self.pagination = pagination
        self.links = links
        self.disruptions = disruptions
        self.notes = notes
        self.arrivals = arrivals
        self.feedPublishers = feedPublishers
        self.context = context
        self.error = error
        self.exceptions = exceptions
    }

    public enum CodingKeys: String, CodingKey { 
        case pagination
        case links
        case disruptions
        case notes
        case arrivals
        case feedPublishers = "feed_publishers"
        case context
        case error
        case exceptions
    }


}

