//
// CalendarPeriod.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CalendarPeriod: Codable {

    public var begin: String?
    public var end: String?

    public init(begin: String?, end: String?) {
        self.begin = begin
        self.end = end
    }


}

