//
// Cost.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Cost: Codable {

    public var currency: String?
    public var value: String?

    public init(currency: String?, value: String?) {
        self.currency = currency
        self.value = value
    }


}

