//
// Distances.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Distances: Codable {

    /** Total distance by car of the journey (meters) */
    public var car: Int
    /** Total walking distance of the journey (meters) */
    public var walking: Int
    /** Total distance by bike of the journey (meters) */
    public var bike: Int
    /** Total distance by ridesharing of the journey (meters) */
    public var ridesharing: Int

    public init(car: Int, walking: Int, bike: Int, ridesharing: Int) {
        self.car = car
        self.walking = walking
        self.bike = bike
        self.ridesharing = ridesharing
    }


}

