//
// Durations.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Durations: Codable {

    /** Total duration by car of the journey (seconds) */
    public var car: Int
    /** Total walking duration of the journey (seconds) */
    public var walking: Int
    /** Total duration of the journey (seconds) */
    public var total: Int
    /** Total duration by ridesharing of the journey (seconds) */
    public var ridesharing: Int
    /** Total duration by bike of the journey (seconds) */
    public var bike: Int

    public init(car: Int, walking: Int, total: Int, ridesharing: Int, bike: Int) {
        self.car = car
        self.walking = walking
        self.total = total
        self.ridesharing = ridesharing
        self.bike = bike
    }


}

