//
// GeoStatus1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GeoStatus1: Codable {

    public var geoStatus: GeoStatus
    public var context: Context?

    public init(geoStatus: GeoStatus, context: Context?) {
        self.geoStatus = geoStatus
        self.context = context
    }

    public enum CodingKeys: String, CodingKey { 
        case geoStatus = "geo_status"
        case context
    }


}

