//
// HeatMap.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct HeatMap: Codable {

    public var to: Place?
    public var requestedDateTime: String?
    public var from: Place?
    public var heatMatrix: HeatMatrixSchema?

    public init(to: Place?, requestedDateTime: String?, from: Place?, heatMatrix: HeatMatrixSchema?) {
        self.to = to
        self.requestedDateTime = requestedDateTime
        self.from = from
        self.heatMatrix = heatMatrix
    }

    public enum CodingKeys: String, CodingKey { 
        case to
        case requestedDateTime = "requested_date_time"
        case from
        case heatMatrix = "heat_matrix"
    }


}

