//
// JourneyPatterns.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct JourneyPatterns: Codable {

    public var pagination: Pagination
    public var context: Context?
    public var links: [LinkSchema]?
    public var disruptions: [Disruption]
    public var notes: [Note]?
    public var feedPublishers: [FeedPublisher]
    public var journeyPatterns: [JourneyPattern]?
    public var error: ModelError?

    public init(pagination: Pagination, context: Context?, links: [LinkSchema]?, disruptions: [Disruption], notes: [Note]?, feedPublishers: [FeedPublisher], journeyPatterns: [JourneyPattern]?, error: ModelError?) {
        self.pagination = pagination
        self.context = context
        self.links = links
        self.disruptions = disruptions
        self.notes = notes
        self.feedPublishers = feedPublishers
        self.journeyPatterns = journeyPatterns
        self.error = error
    }

    public enum CodingKeys: String, CodingKey { 
        case pagination
        case context
        case links
        case disruptions
        case notes
        case feedPublishers = "feed_publishers"
        case journeyPatterns = "journey_patterns"
        case error
    }


}

