//
// MultiLineStringSchema.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MultiLineStringSchema: Codable {

    public var type: String?
    public var coordinates: [[[Float]]]?

    public init(type: String?, coordinates: [[[Float]]]?) {
        self.type = type
        self.coordinates = coordinates
    }


}

