//
// Route.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Route: Codable {

    public enum IsFrequence: String, Codable { 
        case _false = "False"
    }
    public var direction: Place?
    public var codes: [Code]?
    /** Name of the object */
    public var name: String
    public var links: [LinkSchema]
    public var physicalModes: [PhysicalMode]?
    public var isFrequence: IsFrequence?
    public var comments: [Comment]?
    public var directionType: String
    public var geojson: MultiLineStringSchema?
    public var stopPoints: [StopPoint]?
    public var line: Line?
    /** Identifier of the object */
    public var _id: String

    public init(direction: Place?, codes: [Code]?, name: String, links: [LinkSchema], physicalModes: [PhysicalMode]?, isFrequence: IsFrequence?, comments: [Comment]?, directionType: String, geojson: MultiLineStringSchema?, stopPoints: [StopPoint]?, line: Line?, _id: String) {
        self.direction = direction
        self.codes = codes
        self.name = name
        self.links = links
        self.physicalModes = physicalModes
        self.isFrequence = isFrequence
        self.comments = comments
        self.directionType = directionType
        self.geojson = geojson
        self.stopPoints = stopPoints
        self.line = line
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey { 
        case direction
        case codes
        case name
        case links
        case physicalModes = "physical_modes"
        case isFrequence = "is_frequence"
        case comments
        case directionType = "direction_type"
        case geojson
        case stopPoints = "stop_points"
        case line
        case _id = "id"
    }


}

