//
// RouteDisplayInformation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RouteDisplayInformation: Codable {

    public var direction: String
    public var code: String?
    public var network: String?
    public var links: [LinkSchema]
    public var color: String?
    public var label: String?
    public var commercialMode: String?
    public var textColor: String?
    public var name: String?

    public init(direction: String, code: String?, network: String?, links: [LinkSchema], color: String?, label: String?, commercialMode: String?, textColor: String?, name: String?) {
        self.direction = direction
        self.code = code
        self.network = network
        self.links = links
        self.color = color
        self.label = label
        self.commercialMode = commercialMode
        self.textColor = textColor
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case direction
        case code
        case network
        case links
        case color
        case label
        case commercialMode = "commercial_mode"
        case textColor = "text_color"
        case name
    }


}

