//
// Row.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Row: Codable {

    public var stopPoint: StopPoint?
    public var dateTimes: [DateTimeType]

    public init(stopPoint: StopPoint?, dateTimes: [DateTimeType]) {
        self.stopPoint = stopPoint
        self.dateTimes = dateTimes
    }

    public enum CodingKeys: String, CodingKey { 
        case stopPoint = "stop_point"
        case dateTimes = "date_times"
    }


}

