//
// SectionGeoJsonSchemaProperties.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SectionGeoJsonSchemaProperties: Codable {

    public var length: Double?

    public init(length: Double?) {
        self.length = length
    }


}

