//
// SectionGeoJsonSchema.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SectionGeoJsonSchema: Codable {

    public var type: String?
    public var properties: [SectionGeoJsonSchemaProperties]?
    public var coordinates: [[Float]]?

    public init(type: String?, properties: [SectionGeoJsonSchemaProperties]?, coordinates: [[Float]]?) {
        self.type = type
        self.properties = properties
        self.coordinates = coordinates
    }


}

