//
// CurrentAvailability.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class CurrentAvailability: JSONEncodable, Mappable {

    public enum Status: String { 
        case unknown = "unknown"
        case available = "available"
        case unavailable = "unavailable"
    }
    public var status: Status?
    public var effect: Effect?
    public var cause: Cause?
    public var periods: [Period]?
    public var updatedAt: String?

    public init() {}
    required public init?(map: Map) {

    }


    public func mapping(map: Map) {
        status <- map["status"]
        effect <- map["effect"]
        cause <- map["cause"]
        periods <- map["periods"]
        updatedAt <- map["updated_at"]
    }

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["status"] = self.status?.rawValue
        nillableDictionary["effect"] = self.effect?.encodeToJSON()
        nillableDictionary["cause"] = self.cause?.encodeToJSON()
        nillableDictionary["periods"] = self.periods?.encodeToJSON()
        nillableDictionary["updated_at"] = self.updatedAt

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
