//
// EquipmentReport.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class EquipmentReport: JSONEncodable, Mappable {

    public var line: Line?
    public var stopAreaEquipments: [StopAreaEquipments]?

    public init() {}
    required public init?(map: Map) {

    }


    public func mapping(map: Map) {
        line <- map["line"]
        stopAreaEquipments <- map["stop_area_equipments"]
    }

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["line"] = self.line?.encodeToJSON()
        nillableDictionary["stop_area_equipments"] = self.stopAreaEquipments?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
