//
// StopSchedules.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import ObjectMapper


open class StopSchedules: JSONEncodable, Mappable {

    public var stopSchedules: [StopSchedule]?
    public var pagination: Pagination?
    public var feedPublishers: [FeedPublisher]?
    public var error: ModelError?
    public var disruptions: [Disruption]?

    public init() {}
    required public init?(map: Map) {

    }


    public func mapping(map: Map) {
        stopSchedules <- map["stop_schedules"]
        pagination <- map["pagination"]
        feedPublishers <- map["feed_publishers"]
        error <- map["error"]
        disruptions <- map["disruptions"]
    }

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["stop_schedules"] = self.stopSchedules?.encodeToJSON()
        nillableDictionary["pagination"] = self.pagination?.encodeToJSON()
        nillableDictionary["feed_publishers"] = self.feedPublishers?.encodeToJSON()
        nillableDictionary["error"] = self.error?.encodeToJSON()
        nillableDictionary["disruptions"] = self.disruptions?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
