//
// JourneysAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class JourneysAPI {
    public enum DatetimeRepresents_getCoverageLonLatJourneys: String { 
        case arrival = "arrival"
        case departure = "departure"
    }

    public enum FirstSectionMode_getCoverageLonLatJourneys: String { 
        case walking = "walking"
        case car = "car"
        case bike = "bike"
        case bss = "bss"
        case ridesharing = "ridesharing"
    }

    public enum LastSectionMode_getCoverageLonLatJourneys: String { 
        case walking = "walking"
        case car = "car"
        case bike = "bike"
        case bss = "bss"
        case ridesharing = "ridesharing"
    }

    public enum DataFreshness_getCoverageLonLatJourneys: String { 
        case baseSchedule = "base_schedule"
        case adaptedSchedule = "adapted_schedule"
        case realtime = "realtime"
    }

    public enum TravelerType_getCoverageLonLatJourneys: String { 
        case cyclist = "cyclist"
        case luggage = "luggage"
        case wheelchair = "wheelchair"
        case standard = "standard"
        case motorist = "motorist"
        case fastWalker = "fast_walker"
        case slowWalker = "slow_walker"
    }

    public enum DirectPath_getCoverageLonLatJourneys: String { 
        case indifferent = "indifferent"
        case only = "only"
        case _none = "none"
    }

    public enum AddPoiInfos_getCoverageLonLatJourneys: String { 
        case bssStands = "bss_stands"
        case carPark = "car_park"
        case empty = ""
        case _none = "none"
    }


    open class func getCoverageLonLatJourneys(lat: Double, lon: Double, from: String? = nil, to: String? = nil, datetime: Date? = nil, datetimeRepresents: DatetimeRepresents_getCoverageLonLatJourneys? = nil, maxNbTransfers: Int? = nil, minNbTransfers: Int? = nil, firstSectionMode: [String]? = nil, lastSectionMode: [String]? = nil, maxDurationToPt: Int? = nil, maxWalkingDurationToPt: Int? = nil, maxBikeDurationToPt: Int? = nil, maxBssDurationToPt: Int? = nil, maxCarDurationToPt: Int? = nil, maxRidesharingDurationToPt: Int? = nil, walkingSpeed: Float? = nil, bikeSpeed: Float? = nil, bssSpeed: Float? = nil, carSpeed: Float? = nil, ridesharingSpeed: Float? = nil, forbiddenUris: [String]? = nil, allowedId: [String]? = nil, disruptionActive: Bool? = nil, dataFreshness: DataFreshness_getCoverageLonLatJourneys? = nil, maxDuration: Int? = nil, wheelchair: Bool? = nil, travelerType: TravelerType_getCoverageLonLatJourneys? = nil, directPath: DirectPath_getCoverageLonLatJourneys? = nil, freeRadiusFrom: Int? = nil, freeRadiusTo: Int? = nil, count: Int? = nil, isJourneySchedules: Bool? = nil, minNbJourneys: Int? = nil, maxNbJourneys: Int? = nil, bssStands: Bool? = nil, addPoiInfos: [String]? = nil, timeframeDuration: Int? = nil, completion: @escaping ((_ data: Journeys?,_ error: Error?) -> Void)) {
        getCoverageLonLatJourneysWithRequestBuilder(lat: lat, lon: lon, from: from, to: to, datetime: datetime, datetimeRepresents: datetimeRepresents, maxNbTransfers: maxNbTransfers, minNbTransfers: minNbTransfers, firstSectionMode: firstSectionMode, lastSectionMode: lastSectionMode, maxDurationToPt: maxDurationToPt, maxWalkingDurationToPt: maxWalkingDurationToPt, maxBikeDurationToPt: maxBikeDurationToPt, maxBssDurationToPt: maxBssDurationToPt, maxCarDurationToPt: maxCarDurationToPt, maxRidesharingDurationToPt: maxRidesharingDurationToPt, walkingSpeed: walkingSpeed, bikeSpeed: bikeSpeed, bssSpeed: bssSpeed, carSpeed: carSpeed, ridesharingSpeed: ridesharingSpeed, forbiddenUris: forbiddenUris, allowedId: allowedId, disruptionActive: disruptionActive, dataFreshness: dataFreshness, maxDuration: maxDuration, wheelchair: wheelchair, travelerType: travelerType, directPath: directPath, freeRadiusFrom: freeRadiusFrom, freeRadiusTo: freeRadiusTo, count: count, isJourneySchedules: isJourneySchedules, minNbJourneys: minNbJourneys, maxNbJourneys: maxNbJourneys, bssStands: bssStands, addPoiInfos: addPoiInfos, timeframeDuration: timeframeDuration).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    open class func getCoverageLonLatJourneysWithRequestBuilder(lat: Double, lon: Double, from: String? = nil, to: String? = nil, datetime: Date? = nil, datetimeRepresents: DatetimeRepresents_getCoverageLonLatJourneys? = nil, maxNbTransfers: Int? = nil, minNbTransfers: Int? = nil, firstSectionMode: [String]? = nil, lastSectionMode: [String]? = nil, maxDurationToPt: Int? = nil, maxWalkingDurationToPt: Int? = nil, maxBikeDurationToPt: Int? = nil, maxBssDurationToPt: Int? = nil, maxCarDurationToPt: Int? = nil, maxRidesharingDurationToPt: Int? = nil, walkingSpeed: Float? = nil, bikeSpeed: Float? = nil, bssSpeed: Float? = nil, carSpeed: Float? = nil, ridesharingSpeed: Float? = nil, forbiddenUris: [String]? = nil, allowedId: [String]? = nil, disruptionActive: Bool? = nil, dataFreshness: DataFreshness_getCoverageLonLatJourneys? = nil, maxDuration: Int? = nil, wheelchair: Bool? = nil, travelerType: TravelerType_getCoverageLonLatJourneys? = nil, directPath: DirectPath_getCoverageLonLatJourneys? = nil, freeRadiusFrom: Int? = nil, freeRadiusTo: Int? = nil, count: Int? = nil, isJourneySchedules: Bool? = nil, minNbJourneys: Int? = nil, maxNbJourneys: Int? = nil, bssStands: Bool? = nil, addPoiInfos: [String]? = nil, timeframeDuration: Int? = nil) -> RequestBuilder<Journeys> {
        var path = "/coverage/{lon};{lat}/journeys"
        let latPreEscape = "\(lat)"
        let latPostEscape = latPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{lat}", with: latPostEscape, options: .literal, range: nil)
        let lonPreEscape = "\(lon)"
        let lonPostEscape = lonPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{lon}", with: lonPostEscape, options: .literal, range: nil)
        let URLString = NavitiaSDK.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "from": from, 
            "to": to, 
            "datetime": datetime?.encodeToJSON(), 
            "datetime_represents": datetimeRepresents?.rawValue, 
            "max_nb_transfers": maxNbTransfers?.encodeToJSON(), 
            "min_nb_transfers": minNbTransfers?.encodeToJSON(), 
            "first_section_mode[]": firstSectionMode, 
            "last_section_mode[]": lastSectionMode, 
            "max_duration_to_pt": maxDurationToPt?.encodeToJSON(), 
            "max_walking_duration_to_pt": maxWalkingDurationToPt?.encodeToJSON(), 
            "max_bike_duration_to_pt": maxBikeDurationToPt?.encodeToJSON(), 
            "max_bss_duration_to_pt": maxBssDurationToPt?.encodeToJSON(), 
            "max_car_duration_to_pt": maxCarDurationToPt?.encodeToJSON(), 
            "max_ridesharing_duration_to_pt": maxRidesharingDurationToPt?.encodeToJSON(), 
            "walking_speed": walkingSpeed, 
            "bike_speed": bikeSpeed, 
            "bss_speed": bssSpeed, 
            "car_speed": carSpeed, 
            "ridesharing_speed": ridesharingSpeed, 
            "forbidden_uris[]": forbiddenUris, 
            "allowed_id[]": allowedId, 
            "disruption_active": disruptionActive, 
            "data_freshness": dataFreshness?.rawValue, 
            "max_duration": maxDuration?.encodeToJSON(), 
            "wheelchair": wheelchair, 
            "traveler_type": travelerType?.rawValue, 
            "direct_path": directPath?.rawValue, 
            "free_radius_from": freeRadiusFrom?.encodeToJSON(), 
            "free_radius_to": freeRadiusTo?.encodeToJSON(), 
            "count": count?.encodeToJSON(), 
            "is_journey_schedules": isJourneySchedules, 
            "min_nb_journeys": minNbJourneys?.encodeToJSON(), 
            "max_nb_journeys": maxNbJourneys?.encodeToJSON(), 
            "bss_stands": bssStands, 
            "add_poi_infos[]": addPoiInfos, 
            "timeframe_duration": timeframeDuration?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<Journeys>.Type = NavitiaSDK.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false).addCredential()
    }

    public enum DatetimeRepresents_getCoverageRegionJourneys: String { 
        case arrival = "arrival"
        case departure = "departure"
    }

    public enum FirstSectionMode_getCoverageRegionJourneys: String { 
        case walking = "walking"
        case car = "car"
        case bike = "bike"
        case bss = "bss"
        case ridesharing = "ridesharing"
    }

    public enum LastSectionMode_getCoverageRegionJourneys: String { 
        case walking = "walking"
        case car = "car"
        case bike = "bike"
        case bss = "bss"
        case ridesharing = "ridesharing"
    }

    public enum DataFreshness_getCoverageRegionJourneys: String { 
        case baseSchedule = "base_schedule"
        case adaptedSchedule = "adapted_schedule"
        case realtime = "realtime"
    }

    public enum TravelerType_getCoverageRegionJourneys: String { 
        case cyclist = "cyclist"
        case luggage = "luggage"
        case wheelchair = "wheelchair"
        case standard = "standard"
        case motorist = "motorist"
        case fastWalker = "fast_walker"
        case slowWalker = "slow_walker"
    }

    public enum DirectPath_getCoverageRegionJourneys: String { 
        case indifferent = "indifferent"
        case only = "only"
        case _none = "none"
    }

    public enum AddPoiInfos_getCoverageRegionJourneys: String { 
        case bssStands = "bss_stands"
        case carPark = "car_park"
        case empty = ""
        case _none = "none"
    }


    open class func getCoverageRegionJourneys(region: String, from: String? = nil, to: String? = nil, datetime: Date? = nil, datetimeRepresents: DatetimeRepresents_getCoverageRegionJourneys? = nil, maxNbTransfers: Int? = nil, minNbTransfers: Int? = nil, firstSectionMode: [String]? = nil, lastSectionMode: [String]? = nil, maxDurationToPt: Int? = nil, maxWalkingDurationToPt: Int? = nil, maxBikeDurationToPt: Int? = nil, maxBssDurationToPt: Int? = nil, maxCarDurationToPt: Int? = nil, maxRidesharingDurationToPt: Int? = nil, walkingSpeed: Float? = nil, bikeSpeed: Float? = nil, bssSpeed: Float? = nil, carSpeed: Float? = nil, ridesharingSpeed: Float? = nil, forbiddenUris: [String]? = nil, allowedId: [String]? = nil, disruptionActive: Bool? = nil, dataFreshness: DataFreshness_getCoverageRegionJourneys? = nil, maxDuration: Int? = nil, wheelchair: Bool? = nil, travelerType: TravelerType_getCoverageRegionJourneys? = nil, directPath: DirectPath_getCoverageRegionJourneys? = nil, freeRadiusFrom: Int? = nil, freeRadiusTo: Int? = nil, count: Int? = nil, isJourneySchedules: Bool? = nil, minNbJourneys: Int? = nil, maxNbJourneys: Int? = nil, bssStands: Bool? = nil, addPoiInfos: [String]? = nil, timeframeDuration: Int? = nil, completion: @escaping ((_ data: Journeys?,_ error: Error?) -> Void)) {
        getCoverageRegionJourneysWithRequestBuilder(region: region, from: from, to: to, datetime: datetime, datetimeRepresents: datetimeRepresents, maxNbTransfers: maxNbTransfers, minNbTransfers: minNbTransfers, firstSectionMode: firstSectionMode, lastSectionMode: lastSectionMode, maxDurationToPt: maxDurationToPt, maxWalkingDurationToPt: maxWalkingDurationToPt, maxBikeDurationToPt: maxBikeDurationToPt, maxBssDurationToPt: maxBssDurationToPt, maxCarDurationToPt: maxCarDurationToPt, maxRidesharingDurationToPt: maxRidesharingDurationToPt, walkingSpeed: walkingSpeed, bikeSpeed: bikeSpeed, bssSpeed: bssSpeed, carSpeed: carSpeed, ridesharingSpeed: ridesharingSpeed, forbiddenUris: forbiddenUris, allowedId: allowedId, disruptionActive: disruptionActive, dataFreshness: dataFreshness, maxDuration: maxDuration, wheelchair: wheelchair, travelerType: travelerType, directPath: directPath, freeRadiusFrom: freeRadiusFrom, freeRadiusTo: freeRadiusTo, count: count, isJourneySchedules: isJourneySchedules, minNbJourneys: minNbJourneys, maxNbJourneys: maxNbJourneys, bssStands: bssStands, addPoiInfos: addPoiInfos, timeframeDuration: timeframeDuration).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    open class func getCoverageRegionJourneysWithRequestBuilder(region: String, from: String? = nil, to: String? = nil, datetime: Date? = nil, datetimeRepresents: DatetimeRepresents_getCoverageRegionJourneys? = nil, maxNbTransfers: Int? = nil, minNbTransfers: Int? = nil, firstSectionMode: [String]? = nil, lastSectionMode: [String]? = nil, maxDurationToPt: Int? = nil, maxWalkingDurationToPt: Int? = nil, maxBikeDurationToPt: Int? = nil, maxBssDurationToPt: Int? = nil, maxCarDurationToPt: Int? = nil, maxRidesharingDurationToPt: Int? = nil, walkingSpeed: Float? = nil, bikeSpeed: Float? = nil, bssSpeed: Float? = nil, carSpeed: Float? = nil, ridesharingSpeed: Float? = nil, forbiddenUris: [String]? = nil, allowedId: [String]? = nil, disruptionActive: Bool? = nil, dataFreshness: DataFreshness_getCoverageRegionJourneys? = nil, maxDuration: Int? = nil, wheelchair: Bool? = nil, travelerType: TravelerType_getCoverageRegionJourneys? = nil, directPath: DirectPath_getCoverageRegionJourneys? = nil, freeRadiusFrom: Int? = nil, freeRadiusTo: Int? = nil, count: Int? = nil, isJourneySchedules: Bool? = nil, minNbJourneys: Int? = nil, maxNbJourneys: Int? = nil, bssStands: Bool? = nil, addPoiInfos: [String]? = nil, timeframeDuration: Int? = nil) -> RequestBuilder<Journeys> {
        var path = "/coverage/{region}/journeys"
        let regionPreEscape = "\(region)"
        let regionPostEscape = regionPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{region}", with: regionPostEscape, options: .literal, range: nil)
        let URLString = NavitiaSDK.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "from": from, 
            "to": to, 
            "datetime": datetime?.encodeToJSON(), 
            "datetime_represents": datetimeRepresents?.rawValue, 
            "max_nb_transfers": maxNbTransfers?.encodeToJSON(), 
            "min_nb_transfers": minNbTransfers?.encodeToJSON(), 
            "first_section_mode[]": firstSectionMode, 
            "last_section_mode[]": lastSectionMode, 
            "max_duration_to_pt": maxDurationToPt?.encodeToJSON(), 
            "max_walking_duration_to_pt": maxWalkingDurationToPt?.encodeToJSON(), 
            "max_bike_duration_to_pt": maxBikeDurationToPt?.encodeToJSON(), 
            "max_bss_duration_to_pt": maxBssDurationToPt?.encodeToJSON(), 
            "max_car_duration_to_pt": maxCarDurationToPt?.encodeToJSON(), 
            "max_ridesharing_duration_to_pt": maxRidesharingDurationToPt?.encodeToJSON(), 
            "walking_speed": walkingSpeed, 
            "bike_speed": bikeSpeed, 
            "bss_speed": bssSpeed, 
            "car_speed": carSpeed, 
            "ridesharing_speed": ridesharingSpeed, 
            "forbidden_uris[]": forbiddenUris, 
            "allowed_id[]": allowedId, 
            "disruption_active": disruptionActive, 
            "data_freshness": dataFreshness?.rawValue, 
            "max_duration": maxDuration?.encodeToJSON(), 
            "wheelchair": wheelchair, 
            "traveler_type": travelerType?.rawValue, 
            "direct_path": directPath?.rawValue, 
            "free_radius_from": freeRadiusFrom?.encodeToJSON(), 
            "free_radius_to": freeRadiusTo?.encodeToJSON(), 
            "count": count?.encodeToJSON(), 
            "is_journey_schedules": isJourneySchedules, 
            "min_nb_journeys": minNbJourneys?.encodeToJSON(), 
            "max_nb_journeys": maxNbJourneys?.encodeToJSON(), 
            "bss_stands": bssStands, 
            "add_poi_infos[]": addPoiInfos, 
            "timeframe_duration": timeframeDuration?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<Journeys>.Type = NavitiaSDK.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false).addCredential()
    }

    public enum DatetimeRepresents_getJourneys: String { 
        case arrival = "arrival"
        case departure = "departure"
    }

    public enum FirstSectionMode_getJourneys: String { 
        case walking = "walking"
        case car = "car"
        case bike = "bike"
        case bss = "bss"
        case ridesharing = "ridesharing"
    }

    public enum LastSectionMode_getJourneys: String { 
        case walking = "walking"
        case car = "car"
        case bike = "bike"
        case bss = "bss"
        case ridesharing = "ridesharing"
    }

    public enum DataFreshness_getJourneys: String { 
        case baseSchedule = "base_schedule"
        case adaptedSchedule = "adapted_schedule"
        case realtime = "realtime"
    }

    public enum TravelerType_getJourneys: String { 
        case cyclist = "cyclist"
        case luggage = "luggage"
        case wheelchair = "wheelchair"
        case standard = "standard"
        case motorist = "motorist"
        case fastWalker = "fast_walker"
        case slowWalker = "slow_walker"
    }

    public enum DirectPath_getJourneys: String { 
        case indifferent = "indifferent"
        case only = "only"
        case _none = "none"
    }

    public enum AddPoiInfos_getJourneys: String { 
        case bssStands = "bss_stands"
        case carPark = "car_park"
        case empty = ""
        case _none = "none"
    }


    open class func getJourneys(from: String? = nil, to: String? = nil, datetime: Date? = nil, datetimeRepresents: DatetimeRepresents_getJourneys? = nil, maxNbTransfers: Int? = nil, minNbTransfers: Int? = nil, firstSectionMode: [String]? = nil, lastSectionMode: [String]? = nil, maxDurationToPt: Int? = nil, maxWalkingDurationToPt: Int? = nil, maxBikeDurationToPt: Int? = nil, maxBssDurationToPt: Int? = nil, maxCarDurationToPt: Int? = nil, maxRidesharingDurationToPt: Int? = nil, walkingSpeed: Float? = nil, bikeSpeed: Float? = nil, bssSpeed: Float? = nil, carSpeed: Float? = nil, ridesharingSpeed: Float? = nil, forbiddenUris: [String]? = nil, allowedId: [String]? = nil, disruptionActive: Bool? = nil, dataFreshness: DataFreshness_getJourneys? = nil, maxDuration: Int? = nil, wheelchair: Bool? = nil, travelerType: TravelerType_getJourneys? = nil, directPath: DirectPath_getJourneys? = nil, freeRadiusFrom: Int? = nil, freeRadiusTo: Int? = nil, count: Int? = nil, isJourneySchedules: Bool? = nil, minNbJourneys: Int? = nil, maxNbJourneys: Int? = nil, bssStands: Bool? = nil, addPoiInfos: [String]? = nil, timeframeDuration: Int? = nil, completion: @escaping ((_ data: Journeys?,_ error: Error?) -> Void)) {
        getJourneysWithRequestBuilder(from: from, to: to, datetime: datetime, datetimeRepresents: datetimeRepresents, maxNbTransfers: maxNbTransfers, minNbTransfers: minNbTransfers, firstSectionMode: firstSectionMode, lastSectionMode: lastSectionMode, maxDurationToPt: maxDurationToPt, maxWalkingDurationToPt: maxWalkingDurationToPt, maxBikeDurationToPt: maxBikeDurationToPt, maxBssDurationToPt: maxBssDurationToPt, maxCarDurationToPt: maxCarDurationToPt, maxRidesharingDurationToPt: maxRidesharingDurationToPt, walkingSpeed: walkingSpeed, bikeSpeed: bikeSpeed, bssSpeed: bssSpeed, carSpeed: carSpeed, ridesharingSpeed: ridesharingSpeed, forbiddenUris: forbiddenUris, allowedId: allowedId, disruptionActive: disruptionActive, dataFreshness: dataFreshness, maxDuration: maxDuration, wheelchair: wheelchair, travelerType: travelerType, directPath: directPath, freeRadiusFrom: freeRadiusFrom, freeRadiusTo: freeRadiusTo, count: count, isJourneySchedules: isJourneySchedules, minNbJourneys: minNbJourneys, maxNbJourneys: maxNbJourneys, bssStands: bssStands, addPoiInfos: addPoiInfos, timeframeDuration: timeframeDuration).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    open class func getJourneysWithRequestBuilder(from: String? = nil, to: String? = nil, datetime: Date? = nil, datetimeRepresents: DatetimeRepresents_getJourneys? = nil, maxNbTransfers: Int? = nil, minNbTransfers: Int? = nil, firstSectionMode: [String]? = nil, lastSectionMode: [String]? = nil, maxDurationToPt: Int? = nil, maxWalkingDurationToPt: Int? = nil, maxBikeDurationToPt: Int? = nil, maxBssDurationToPt: Int? = nil, maxCarDurationToPt: Int? = nil, maxRidesharingDurationToPt: Int? = nil, walkingSpeed: Float? = nil, bikeSpeed: Float? = nil, bssSpeed: Float? = nil, carSpeed: Float? = nil, ridesharingSpeed: Float? = nil, forbiddenUris: [String]? = nil, allowedId: [String]? = nil, disruptionActive: Bool? = nil, dataFreshness: DataFreshness_getJourneys? = nil, maxDuration: Int? = nil, wheelchair: Bool? = nil, travelerType: TravelerType_getJourneys? = nil, directPath: DirectPath_getJourneys? = nil, freeRadiusFrom: Int? = nil, freeRadiusTo: Int? = nil, count: Int? = nil, isJourneySchedules: Bool? = nil, minNbJourneys: Int? = nil, maxNbJourneys: Int? = nil, bssStands: Bool? = nil, addPoiInfos: [String]? = nil, timeframeDuration: Int? = nil) -> RequestBuilder<Journeys> {
        let path = "/journeys"
        let URLString = NavitiaSDK.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "from": from, 
            "to": to, 
            "datetime": datetime?.encodeToJSON(), 
            "datetime_represents": datetimeRepresents?.rawValue, 
            "max_nb_transfers": maxNbTransfers?.encodeToJSON(), 
            "min_nb_transfers": minNbTransfers?.encodeToJSON(), 
            "first_section_mode[]": firstSectionMode, 
            "last_section_mode[]": lastSectionMode, 
            "max_duration_to_pt": maxDurationToPt?.encodeToJSON(), 
            "max_walking_duration_to_pt": maxWalkingDurationToPt?.encodeToJSON(), 
            "max_bike_duration_to_pt": maxBikeDurationToPt?.encodeToJSON(), 
            "max_bss_duration_to_pt": maxBssDurationToPt?.encodeToJSON(), 
            "max_car_duration_to_pt": maxCarDurationToPt?.encodeToJSON(), 
            "max_ridesharing_duration_to_pt": maxRidesharingDurationToPt?.encodeToJSON(), 
            "walking_speed": walkingSpeed, 
            "bike_speed": bikeSpeed, 
            "bss_speed": bssSpeed, 
            "car_speed": carSpeed, 
            "ridesharing_speed": ridesharingSpeed, 
            "forbidden_uris[]": forbiddenUris, 
            "allowed_id[]": allowedId, 
            "disruption_active": disruptionActive, 
            "data_freshness": dataFreshness?.rawValue, 
            "max_duration": maxDuration?.encodeToJSON(), 
            "wheelchair": wheelchair, 
            "traveler_type": travelerType?.rawValue, 
            "direct_path": directPath?.rawValue, 
            "free_radius_from": freeRadiusFrom?.encodeToJSON(), 
            "free_radius_to": freeRadiusTo?.encodeToJSON(), 
            "count": count?.encodeToJSON(), 
            "is_journey_schedules": isJourneySchedules, 
            "min_nb_journeys": minNbJourneys?.encodeToJSON(), 
            "max_nb_journeys": maxNbJourneys?.encodeToJSON(), 
            "bss_stands": bssStands, 
            "add_poi_infos[]": addPoiInfos, 
            "timeframe_duration": timeframeDuration?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<Journeys>.Type = NavitiaSDK.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false).addCredential()
    }

}
